((nil . ((indent-tabs-mode . nil)
         (fill-column . 100)
         (hexboard-cc-style
          .
          ("hexboard"
           (c-basic-offset . 2)
           (c-comment-only-line-offset . 0)
           (c-offsets-alist
            (defun-block-intro . 2)
            (block-open . 0)
            (substatement-open . 0)
            (statement-cont . +)
            (case-label . 0)
            (access-label . -2)
            (statement-case-intro . +)
            (statement-case-open . +)
            (arglist-intro . +)
            (arglist-close . 0)
            (inline-open . 0)
            (inlambda . 0)
           )
          )
         )
        )
 )
 (c++-mode . ((eval . (progn
                        (add-to-list 'c-style-alist hexboard-cc-style)
                        (c-set-style "hexboard")
                      )
              ))
 )
 (c-mode . ((eval . (progn
                      (add-to-list 'c-style-alist hexboard-cc-style)
                      (c-set-style "hexboard")
                    )
            ))
 )
 (arduino-mode . ((eval . (progn
                      (add-to-list 'c-style-alist hexboard-cc-style)
                      (c-set-style "hexboard")
                    )
            ))
 )
)
