import {odeOpening, odeClosing, odeEvenBeats, odeClosingBeats, twinkleOpening, twinklePhrase, twinkleBeats, auClairOpening, auClairBeats, joyDescending} from "./courseMelodies.ts";
import type {CourseLesson} from "./beginnerCourse.ts";
import {courseFormat, type UserCourse} from "./courseFiles.ts";
import {majorScale, starterLayouts} from "./majorScale.ts";
import {recommendCourseRoute as route} from "./curriculumKeys.ts";

const melody = (notes: number[]) => notes.map(note => [note]);
const page = (id:string, title:string, section:string, markdown:string):CourseLesson => ({id,title,section,kind:"content",markdown,instruction:"",targets:[]});
const play = (id:string, title:string, section:string, instruction:string, notes:number[]):CourseLesson => ({id,title,section,instruction,targets:melody(notes)});
const timed = (lesson:CourseLesson, beats:number[], goalBpm=70):CourseLesson => ({...lesson,timing:{goalBpm,beats}});
const layouts = starterLayouts();
const course = (id:string,title:string,description:string,lessons:CourseLesson[],revision=3):UserCourse => ({
  format:courseFormat,id,revision,title,author:"HexBoard",description,
  bundle:{...layouts[0].bundle,layouts:layouts.map(item=>item.layout)},lessons,
});
const firstTune = odeOpening;
const homeTune = odeClosing;

export const firstStepsCourse = course("hexboard-first-steps","1 · First Steps on HexBoard",
  "Make music with three notes in Au clair de la lune, then play a phrase of Beethoven’s Ode to Joy using five notes. Try a comfortable 5–10 minute session, then return later; there is no deadline. No music reading is needed. Choose one layout and stay with it for now; the same sounds have different physical routes on other layouts.",[
  page("welcome","Welcome: listen, then play","Meet the board","Once HexBoard is connected and the course has started, press the blue **Continue** side button to reach the first exercise. Press cyan **Hear example** to listen before playing. Hum along if the tune is new to you. With hints on, the brightest keys suggest a route. Play one note at a time; there is no time limit.\n\nAfter a familiar phrase, press yellow **Repeat without hints** to try it from memory. Orange **Repeat with hints** brings the bright guide back. Labels and colors remain visible. An Independent star records a clean run without hints or demonstration.\n\nKeep your hand relaxed and release a key before pressing it again. Take a break if your hand gets tired. Finish a session by replaying a phrase you enjoyed."),
  route(play("first-note","Your first note","Meet the board","Play the bright C and listen to its sound. This exercise has no time limit.",[60])),
  route(play("home","Find home","Meet the board","Play C, then G, then C. Listen to how the last note feels like coming home. Hear the example, then answer it yourself.",[60,67,60])),
  route(play("higher-lower","Higher and lower","Meet the board","Play C–D–E, then come down to C. Follow the sound going up and down; higher pitch does not always mean a button directly above the last one.",[60,62,64,62,60])),
  route(play("first-moon-tune","Au clair de la lune: three notes make music","Meet the board","The C, D, and E you know can already make a tune. Hear the opening of the French song Au clair de la lune, then hum and play it. Begin with C–C–C–D–E–D; add C–E–D–D–C when comfortable. Release before each repeated C. You can finish today by replaying this tune.",auClairOpening)),
  route(play("octaves","Two versions of C","Meet the board","Alternate the lower and higher C. They share a name but sound at different heights. This distance is called an octave.",[60,72,60,72,60])),
  play("same-pitch","Same pitch, different button","Choose a route","All matching buttons light equally here. Play the highlighted C♯ (C-sharp), release it, then find another button with exactly the same sound. Repeat with E♭ and F. A higher version of a note is an octave, not a duplicate. These pitches have duplicates on all three layouts. Any matching button counts; changing buttons is your own listening experiment.",[61,61,63,63,65,65]),
  route(play("follow-lights","Follow a short trail","Your first tune","A compact route is highlighted again. Play C–D–E and back, then C–G–C. A duplicate button with the same pitch still counts. Use whichever feels comfortable.",[60,62,64,62,60,67,60])),
  route(play("five-note-tune","Ode to Joy: the opening","Your first tune","Hear the example, then hum and play E–E–F–G, followed by G–F–E–D. These are the opening notes of Beethoven’s Ode to Joy. Release before repeated notes. Learn one four-note group at a time, then join them.",firstTune)),
  route(play("remember-tune","Remember the tune","Your first tune","Press yellow Repeat without hints to start from memory. Recall the opening of Ode to Joy before listening again. If you get stuck, press orange Repeat with hints, practice the four-note group that needs help, and try again. Return to this melody in your next session, too.",firstTune)),
  route(timed(play("first-beat","Ode to Joy: meet the pulse","Your first tune","You already know the notes. After four count-in clicks, play one note per click. Use Step to rehearse, or slow the Practice tempo; reach 60 BPM when ready. The example uses the goal tempo.",firstTune),Array(8).fill(1),60)),
  route(play("homecoming-rehearsal","Ode to Joy: bring it home","Make music","Add the answer C–C–D–E, then D–C–C to the opening you know. Practice the answer on its own before joining both phrases. This closing phrase is transposed to C; the next lesson uses an even rhythm to make your first performance easier.",homeTune)),
  {...route(timed(play("homecoming","Ode to Joy: your first performance","Make music","Play the closing phrase at 60 BPM with a simplified even rhythm. Let the last C ring for two beats. After a guided success, repeat without hints when you feel ready. End your session by playing the phrase once more.",homeTune),odeEvenBeats,60)),repetitions:1},
],4);

const pair = (id:string,title:string,instruction:string,notes:number[]) => route(play(id,title,"Hear and find intervals",instruction,notes),[{steps:notes.length,root:60,shape:"interval"}]);
const motif = [60,62,64,62,60];
export const movementCourse = course("hexboard-isomorphic-movement","2 · Moving Around an Isomorphic Keyboard",
  "Learn a relationship, recognize its shape, then move it. Start after First Steps. Begin a new session by recalling a few notes of Ode to Joy before using hints. These exercises are untimed so you can watch, listen, and choose a comfortable route.",[
  page("same-shape","What is isomorphic?","Shapes that move","An **interval** is the distance between two pitches. On an isomorphic layout, moving every button of a shape by the same amount preserves its intervals. Think of sliding a small picture across the board. The shape changes between Wicki-Hayden, Harmonic Table, and Gerhard, so practice on one layout at a time.\n\nBegin with nearby pitches, then try a familiar tune. Later, moving to a duplicate root will keep the same pitches; moving to a different pitch will transpose the tune. The whole shape must fit on playable buttons."),
  pair("half-steps","Half-step neighbors","Play C–C♯ and back. A half step is the smallest pitch step in this course's 12-EDO tuning. Listen first; its physical route depends on your layout.",[60,61,60,61,60]),
  pair("whole-steps","Whole-step neighbors","Play C–D and back. This larger pitch step spans two half steps. Notice the direction and distance between the suggested buttons.",[60,62,60,62,60]),
  route(play("moon-travel","Au clair de la lune: a first little move","Hear and find intervals","Recall C–C–C–D–E–D from your first course, then play D–D–D–E–F♯–E. The two whole steps stay the same. F♯ means F-sharp, one half step above F. Listen for the same tune starting higher; the suggested buttons slide the whole shape together.",[...auClairOpening.slice(0,6),...auClairOpening.slice(0,6).map(n=>n+2)]),[{steps:6,root:60},{steps:6,root:62}]),
  pair("major-third","A major third","Play C–E and back. This interval spans four half steps. Hum the sound and trace the movement before repeating it.",[60,64,60,64,60]),
  pair("minor-third","A minor third","Play C–E♭ and back. A minor third spans three half steps. Compare its sound with the previous lesson; change only the upper note.",[60,63,60,63,60]),
  route(play("thirds-answer","A short question and answer","Hear and find intervals","Let the major third ask C–E–C; let the minor third answer C–E♭–C. Repeat both phrases. Hear how one changed note changes the answer.",[60,64,60,60,63,60])),
  pair("fifth","A perfect fifth","Play C–G and back. This seven-half-step interval gives a clear, open sound. Notice its button shape before moving it in a later lesson.",[60,67,60,67,60]),
  pair("octave","The octave shape","Play the two Cs. An octave spans twelve half steps. Trace this route on your layout; do not confuse the upper C with a duplicate of the lower C.",[60,72,60,72,60]),
  route(play("interval-locations","Same interval, another position","Translate a shape","Play C♯–F–C♯ in one position, then follow the same major-third shape in a second position. F is four half steps above C♯, just as E is above C. The pitches are unchanged between positions. Matching duplicates are accepted; following the recommendations lets you see the translation.",[61,65,61,61,65,61]),[{steps:3,root:61,position:0},{steps:3,root:61,position:1}]),
  route(play("move-fifth","Move a fifth to a new root","Translate a shape","Play C–G–C, then D–A–D. The second phrase starts higher, but the suggested buttons preserve the same shape. This is transposition.",[60,67,60,62,69,62]),[{steps:3,root:60},{steps:3,root:62}]),
  route(play("three-note-shape","Three notes become a shape","Translate a shape","Play C–D–E–D–C. Think of two equal whole steps followed by the return. On some layouts this scale route uses a different duplicate than the earlier interval exercise.",motif)),
  route(play("duplicate-route","A second route for the same phrase","Translate a shape","Start the whole-step phrase on C♯: C♯–E♭–F–E♭–C♯. Then move to the second highlighted position and repeat it. The sound stays the same. Look ahead so your hand can reposition without a hurried stretch.",[...motif,...motif].map(n=>n+1)),[{steps:5,root:61,position:0},{steps:5,root:61,position:1}]),
  route(play("transpose-motif","A traveling melody","Make the shape musical","Play the phrase from C, then D, then F. Listen for the same tune at three heights. Follow the recommended buttons to see the same physical shape travel.",[...motif,...motif.map(n=>n+2),...motif.map(n=>n+5)]),[{steps:5,root:60},{steps:5,root:62},{steps:5,root:65}]),
  play("choose-route","Choose your return home","Make the shape musical","All matching buttons are equally bright. Play C–E–G–E–C, then D–F♯–A–F♯–D. Choose duplicates that keep the phrase comfortable. The second phrase has the same intervals as the first.",[60,64,67,64,60,62,66,69,66,62]),
  route(play("twinkle-home","Twinkle: learn one phrase first","Make the shape musical","Before moving this tune, learn its opening in C. Play C–C–G–G–A–A–G. Hear the example and hum it; feel the small G–A step after the opening C–G leap. There is no clock. Repeat just this phrase until it feels comfortable.",twinkleOpening)),
  route(play("twinkle-travel","Twinkle: the same tune in two keys","Make the shape musical","Play the opening of Twinkle, Twinkle, Little Star from C, then from D. Hum it first if you know it; otherwise listen to the example. Keep the shape intact and hear the same melody at a new height.",[...twinkleOpening,...twinkleOpening.map(n=>n+2)]),[{steps:7,root:60},{steps:7,root:62}]),
  {id:"shape-playground",title:"Explore a shape",section:"Make the shape musical",kind:"exploration",instruction:"For 45 seconds, choose a short shape from this course. Repeat it, change its ending, or move it to a new root. Listen for an ending that feels settled. This is free exploration, with no score and no required sequence.",targets:[],exploration:{durationSeconds:45,min:60,max:74,pitchClasses:[0,2,4,5,7,9,11],highlighted:[60,64,67]},assessment:{graded:false}},
  {...route(play("shape-checkpoint","Twinkle: travel without hints","Make the shape musical","Recall the opening of Twinkle from C, then move it to D. Press yellow Repeat without hints when ready and aim for two comfortable clean runs. If the move is awkward, revisit Twinkle: the same tune in two keys. Try recalling it again in your next session.",[...twinkleOpening,...twinkleOpening.map(n=>n+2)]),[{steps:7,root:60},{steps:7,root:62}]),repetitions:2},
]);

const rhythm = (id:string,title:string,instruction:string,notes:number[],beats:number[],goalBpm=70,section="Keep a pulse") => route(timed(play(id,title,section,instruction,notes),beats,goalBpm));
const rhythmPhrase = twinklePhrase;
export const rhythmCourse = course("hexboard-rhythm-fundamentals","3 · Rhythm Fundamentals",
  "Keep a pulse while familiar notes become music. Start after Isomorphic Movement. Rehearse any exercise in Step mode, slow the Practice tempo when needed, and work toward its goal BPM. BPM always counts quarter notes.",[
  page("pulse","Find the pulse before playing","Keep a pulse","Press blue **Continue**, then cyan **Hear example** on the first rhythm lesson. Tap along away from the keys. A beat is the steady pulse; a rhythm places notes and spaces around it.\n\nTimed lessons wait for you to start. Read the instructions, then press orange **Start · hints** or yellow **Start · no hints** when ready. You'll hear four count-in clicks before playing. **Step** waits for notes without a clock. Slower runs give practice feedback; completion needs the goal tempo and a passing score. Note lengths guide your phrasing here; releases are not graded.\n\nBegin each visit with a tune you remember. Tap or hum a new rhythm before adding the keys. Use familiar pitches while you learn each new rhythm. Press orange **Repeat with hints** whenever they help, then yellow **Repeat without hints** for a familiar phrase."),
  rhythm("steady-pulse","One note on the pulse","After four clicks, play C once per click. Release before pressing again. Count 1–2–3–4 twice; let your movement feel small and even.",Array(8).fill(60),Array(8).fill(1),60),
  rhythm("moving-pulse","Move with the beat","Keep the same pulse while playing C–D–E–D–C. The notes are familiar; focus on arriving with each click.",[60,62,64,62,60],[1,1,1,1,4],60),
  rhythm("quarter-notes","Quarter notes at 70","A note on every click is a quarter-note rhythm here. Repeat C four times, then D four times. Keep the spacing even across the change.",[60,60,60,60,62,62,62,62],Array(8).fill(1)),
  rhythm("eighth-notes","Two notes per beat","Count 1-and-2-and. Play the first C on a click and the next halfway to the following click. Keep the pitch fixed while learning this subdivision.",Array(8).fill(60),Array(8).fill(0.5),60),
  route(play("twinkle-answer","Twinkle: learn the answer","Keep a pulse","Recall C–C–G–G–A–A–G from the previous course. Add F–F–E–E–D–D–C. Hum the answer, play it slowly, then join it to the opening. There is no clock yet.",rhythmPhrase)),
  rhythm("pulse-tune","Twinkle: long and short","Play the two familiar phrases of Twinkle. Most notes last one beat; the G at the end of the opening and the final C last two. Keep counting while they ring.",rhythmPhrase,twinkleBeats,60),
  rhythm("mixed-lengths","Long and short","Alternate quarters and eighths, with room to breathe on G and C. Let the long notes ring; release length is guidance, while the next attack must stay in time.",[60,62,64,67,64,62,60],[1,0.5,0.5,2,1,1,2],70,"Space and accents"),
  route({...timed(play("rests","Make room for silence","Space and accents","Play C–E–G, leave a beat of silence, then answer G–E–C. Release for the written rests. The grader checks that you do not start a new note in a rest; it does not grade the release.",[]),Array(8).fill(1),70),targets:[[60],[64],[67],[],[67],[64],[60],[]]}),
  rhythm("moon-pulse","Au clair de la lune: let it sing","Recall the three-note tune from First Steps. Now play it with the pulse: four one-beat notes, two two-beat notes, four one-beat notes, then C for four beats. The last C fills the space where the reference score rests. Count through the long notes and enjoy how the rhythm gives the tune its shape.",auClairOpening,auClairBeats,60,"Space and accents"),
  rhythm("repeated-notes","Clean repeated notes","Repeat C in quarters, then eighths, and finish on a long C. Release between attacks. Listen for separate, evenly spaced sounds without making larger movements.",Array(9).fill(60),[1,1,1,1,0.5,0.5,0.5,0.5,2],70,"Space and accents"),
  {...rhythm("three-four","A three-beat dance","Count 1–2–3 in each bar. Play C–E–G, then G–E–C, twice. The count-in is still four clicks; begin grouping in threes at the first note.",[60,64,67,67,64,60,60,64,67,67,64,60],Array(12).fill(1),70,"Space and accents"),timeSignature:{numerator:3,denominator:4}},
  route({...timed(play("offbeats","The spaces between clicks","Space and accents","Count 1-and-2-and. Wait on each numbered click, then play C on and. Keep counting during the rests; they make the offbeat audible.",[]),Array(8).fill(0.5),60),targets:[[],[60],[],[60],[],[60],[],[60]]}),
  rhythm("syncopation","Carry across the click","Count the ands. Play C on 1, E on the and of 2, and G on 3. Repeat, then return home. The long first note carries over a click; avoid adding an attack there.",[60,64,67,60,64,60],[1.5,0.5,2,1.5,0.5,2],60,"Space and accents"),
  page("together","Two notes can share a beat","Sound together","For this rhythm exercise, use only C and G, a familiar fifth. First hold them together without a clock. Press both physical keys together, then release them together. The next timed lesson repeats that same pair; full triad construction comes in Chords and Arpeggios."),
  route({id:"together-rehearsal",title:"Hold C and G together",section:"Sound together",instruction:"Hold both bright notes together, then release. Listen to them blend. Take as much time as you need before adding the click.",targets:[[60,67]]}),
  route({id:"chords-on-beat",title:"Together on the beat",section:"Sound together",instruction:"After the count-in, press C and G together every two beats. Release both before the next pair. These are the same two notes you just rehearsed, now arriving together with the pulse.",targets:Array.from({length:4},()=>[60,67]),timing:{goalBpm:60,beats:[2,2,2,2]}}),
  rhythm("short-phrase","Twinkle: remember and play","Before hearing the example, recall the two phrases of Twinkle. Play at 70 BPM and count through the long endings. If you need hints today, use them; come back for a memory run on another day.",rhythmPhrase,twinkleBeats,70,"Sound together"),
  rhythm("triplets","Three notes per beat","Count 1-trip-let, 2-trip-let. Fit three equal C attacks between successive quarter-note clicks. Keep the pitch fixed while learning the new spacing.",Array(12).fill(60),Array(12).fill(1/3),60,"Divide the beat"),
  rhythm("switch-subdivision","From two to three","First fit two equal C notes into one beat: 1-and. Then fit three into the next: 2-trip-let. Finish with a C on beat 3, held for two beats. Tap the change before playing. The pulse stays steady; only the number of notes inside it changes.",Array(6).fill(60),[0.5,0.5,1/3,1/3,1/3,2],60,"Divide the beat"),
  rhythm("subdivision-mix","One, two, then three","Play two quarters, four eighths, then six triplet notes. Each group lasts two beats. Finish on a C held for two beats. Keep the click steady while only the subdivision changes.",Array(13).fill(60),[1,1,0.5,0.5,0.5,0.5,1/3,1/3,1/3,1/3,1/3,1/3,2],60,"Divide the beat"),
  page("compound-pulse","Two ways to count three","A three-note dance","Triplets put three notes inside **one quarter-note beat**. In **6/8**, six eighth notes form two groups of three: **ONE-two-three FOUR-five-six**. Each large pulse lasts three eighths, or one and a half quarter notes.\n\nThe app's click and BPM still count quarters, so they cross the larger pulse. First learn the dance notes without a clock. Then practice six equal eighths on one pitch before adding the melody. Feel the accents on ONE and FOUR; a score cannot tell whether your phrasing dances. Take this section over another visit if the two ways of counting feel confusing."),
  {...route(play("six-eight-rehearsal","Learn the dance without a clock","A three-note dance","Play C–E–G, then G–E–C, twice. Hum ONE-two-three FOUR-five-six and give the first note of each group a little emphasis. These are the notes of the later 6/8 exercise. Keep your hand relaxed; there is no timing assessment yet.",[60,64,67,67,64,60,60,64,67,67,64,60])),timeSignature:{numerator:6,denominator:8}},
  {...rhythm("six-eight-spacing","Six eighths, two larger pulses","Use one pitch while learning the spacing. After the four-click count-in, play twelve even C eighth notes, counting ONE-two-three FOUR-five-six twice. Two notes fit between quarter-note clicks; the accents group every three. Tap or hum before adding the keys.",Array(12).fill(60),Array(12).fill(0.5),70,"A three-note dance"),timeSignature:{numerator:6,denominator:8}},
  {...rhythm("six-eight","A little dance in 6/8","Join the familiar C–E–G / G–E–C melody to the eighth-note spacing you just practiced. Count ONE-two-three FOUR-five-six, twice. Let the two groups feel like a gentle dance. BPM and the click still count quarter notes. Listen once or use Step when you need to reconnect the notes and the grouping.",[60,64,67,67,64,60,60,64,67,67,64,60],Array(12).fill(0.5),70,"A three-note dance"),timeSignature:{numerator:6,denominator:8}},
  rhythm("etude-rehearsal","Ode to Joy: restore the rhythm","Return to the melody from First Steps. This time the ending D lasts a beat and a half, followed by a short C and a final two-beat C. Listen and tap that ending before playing it. Start in Step mode if the notes need refreshing.",odeClosing,odeClosingBeats,60,"Make music"),
  {...rhythm("rhythm-checkpoint","Ode to Joy: final performance","Play the same phrase at 70 BPM for two clean runs. Keep the pulse moving through the dotted ending. Then play it without hints if you like. Notice one thing that sounds better than your first attempt, and choose a favorite tune to revisit next time.",odeClosing,odeClosingBeats,70,"Make music"),repetitions:2},
],4);

const cScale = [...majorScale];
const scaleReturn = [...cScale,...cScale.slice(0,-1).reverse()];
const lowerThirds = [60,64,62,65,64,67];
const scaleThirds = [...lowerThirds,65,69,67,71,69,72];
const dTwinkle = twinklePhrase.map(note=>note+2);
const degrees = (id:string,title:string,instruction:string,notes:number[]) => route(play(id,title,"Give notes jobs",instruction,notes));
export const majorScaleCourse = course("hexboard-major-scale-fluency","4 · Major Scale and Scale-Degree Fluency",
  "Turn a scale into a musical map. Start after Rhythm Fundamentals. Build the C major scale in small groups, hear familiar tunes as degree patterns, then carry the same relationships into D major. Choose one section for a short visit; return to a favorite tune before learning something new. Most exercises have no clock. Finger numbers and chords come in later courses.",[
  page("scale-home","A scale gives a tune a home","Build the scale","Recall Au clair de la lune from your first course before hearing the example. Its three notes belong to **C major**. A scale is an ordered collection of pitches; its **tonic**, or home note, gives this scale its name.\n\nC major goes **C–D–E–F–G–A–B–C**. The upper C is home an octave higher. In 12-EDO its steps follow **whole–whole–half–whole–whole–whole–half**. You already know whole and half steps; find those sounds inside the scale gradually.\n\nPress blue **Continue** to play, or cyan **Hear example** once an exercise is open. Begin with small groups, with no time limit. Choose comfortable duplicates instead of stretching; these highlighted routes are recommendations."),
  route(play("recall-moon","Begin with a tune you remember","Build the scale","Recall Au clair de la lune on C, D, and E. Try humming the opening before playing. Use the example if it has slipped your mind. You already have the beginning of the major scale under your hand.",auClairOpening)),
  route(play("lower-scale","Build the lower half","Build the scale","Play C–D–E–F–G. The steps are whole, whole, half, whole. Listen especially to the smaller E–F step. Pause and repeat that change if needed; there is no clock.",[60,62,64,65,67])),
  route(play("upper-scale","Build the upper half","Build the scale","Begin on G. Play G–A–B–C, then come back to G. The way up uses whole, whole, half steps. The last B–C is small, like E–F in the lower group. The upper C is the same home note an octave higher.",[67,69,71,72,71,69,67])),
  route(play("scale-up","Join the two halves","Build the scale","Join C–D–E–F–G to A–B–C. You only play the joining G once. Hum along and look ahead to the next button. Aim for a relaxed journey to the upper C; even speed can come later.",cScale)),
  route(play("joy-scale","Joy to the World: a scale becomes a tune","Build the scale","The opening of the hymn tune Joy to the World uses the whole major scale coming down: upper C–B–A–G–F–E–D–C. Hear the example for the pitches; it uses equal note lengths here. If you know the tune, hum its rhythm as you play at your own pace. Let the final C feel settled.",joyDescending)),
  route(play("scale-return","Up, down, and home","Build the scale","Travel up the C major scale, then come down without repeating the upper C. Listen for home at both ends. This connects the groups you just learned. Play your favorite tune afterward, or take a break before meeting degree numbers.",scaleReturn)),
  page("degree-map","Names that move with the music","Give notes jobs","A **scale degree** is a note's place in the scale. In C major: **1=C, 2=D, 3=E, 4=F, 5=G, 6=A, 7=B**. The upper C is degree **1** again; **8** is a useful way to count the full ascent. These are musical positions, **not finger numbers**.\n\nDegree 1 is home. Degree 3 is the E you met in a major third; degree 5 is the G in a perfect fifth. Play them separately before making little tunes from these landmarks. You do not need to memorize all seven names in one visit. Say a pattern slowly, then hear and play it."),
  degrees("find-three","Meet degree 3","Say 1–3–1, then play C–E–C. E is degree 3 in C major and a major third above C. Hum it before pressing if you can. Compare the sound of the middle note with the return home.",[60,64,60]),
  degrees("find-five","Meet degree 5","Say 1–5–1, then play C–G–C. G is degree 5 in C major, a perfect fifth above C. This is the home-and-away phrase from First Steps, now with names for each note's job.",[60,67,60]),
  degrees("one-three-five","Three landmarks make a phrase","Play 1–3–5–3–1: C–E–G–E–C. Play one note at a time, letting the line rise and return. These landmarks will help you build chords later; today they make a melody.",[60,64,67,64,60]),
  degrees("ode-degrees","Ode to Joy: hear the degree pattern","Recall Ode to Joy as 3–3–4–5 / 5–4–3–2. In C, those are E–E–F–G / G–F–E–D. Hum the familiar tune and notice that its opening starts on degree 3 rather than home. The numbers describe the tune even when its starting key changes.",odeOpening),
  degrees("scale-half-steps","Find the two smaller steps","Play E–F–E, then B–upper C–B. These are 3–4–3 and 7–8–7, the major scale's two half-step pairs. All its other adjacent steps are whole steps. Listen for how close each pair sounds.",[64,65,64,71,72,71]),
  degrees("degree-walk","A short degree walk","Say 1–2–3–2–1, then play C–D–E–D–C. Try saying the numbers while playing slowly. You are using neighboring scale degrees rather than counting half steps between every note.",[60,62,64,62,60]),
  degrees("degree-turn","Skip, step, and return","Say 1–3–2–4–1 and play C–E–D–F–C. A skip passes over a scale note; a step goes to the neighboring degree. Hear the small E–D step between the skips. Learn the first four notes before adding the return home.",[60,64,62,65,60]),
  degrees("moon-degrees","Au clair de la lune: numbers tell the tune","Play the familiar opening as 1–1–1–2–3–2 / 1–3–2–2–1. In C these are the same notes you recalled at the start. Listen for repeats, steps, and the skip from 1 to 3. You can end this visit with the tune, then recall its first six numbers next time.",auClairOpening),
  route(play("thirds-small","Climb in little pairs","Make the scale flow","Play C–E, D–F, E–G: 1–3, 2–4, 3–5. Each pair skips one scale note. These are scale thirds, and they do not all have the same half-step size: C–E is major, D–F is minor. Let your ear notice the change before extending the pattern.",lowerThirds)),
  route(play("scale-thirds","Continue the pairs upward","Make the scale flow","Continue the same idea through C–E, D–F, E–G, F–A, G–B, A–upper C. Work on the new upper pairs separately, then join them to the three you know. This is an untimed pattern; avoid a hurried stretch and choose a duplicate when it helps.",scaleThirds)),
  route(play("groups-three","Three-note windows","Make the scale flow","Play C–D–E, then D–E–F, then E–F–G. Each little group starts one degree higher and uses neighboring scale notes. The E–F half step means these degree groups are not identical interval shapes. Listen for the overlap instead of sliding one fixed physical shape.",[60,62,64,62,64,65,64,65,67])),
  route(play("groups-four","Four-note windows","Make the scale flow","Play C–D–E–F, then D–E–F–G. Each group has one more note than before. Go slowly enough to look ahead, and let the last G ring. Stop here if the new group needs time to settle; speed is not the goal.",[60,62,64,65,62,64,65,67])),
  route(timed(play("twinkle-c-pulse","Twinkle: put the landmarks in time","Make the scale flow","Return to Twinkle at 60 BPM. Its opening starts 1–1–5–5–6–6–5; the answer comes down 4–4–3–3–2–2–1. You know both the pitches and the rhythm. Keep counting through the two-beat endings and hear how degree 1 brings the answer home.",twinklePhrase),twinkleBeats,60)),
  page("new-home","Give the same degrees a new home","Take the tune to D","In **D major**, degree 1 is D. The scale is **D–E–F♯–G–A–B–C♯–D**: **1–2–3–4–5–6–7–8**. A sharp raises a named note by one half step. F♯ and C♯ keep the same **whole–whole–half–whole–whole–whole–half** pattern you learned in C.\n\nYour layout preserves pitch intervals when you move the complete scale shape. Degree 3 is now F♯, and degree 5 is A. Try the scale and a short degree walk without a clock, then move the familiar Twinkle phrase. You do not need to learn a new tune at the same time as a new key. Press blue **Continue** to try the scale."),
  route(play("d-scale","The same scale shape in D","Take the tune to D","Play D–E–F♯–G–A–B–C♯–upper D. Say 1 through 8. The suggested buttons translate the complete C major route; the smaller steps are still between 3–4 and 7–8. Take your time finding the new home.",cScale.map(note=>note+2)),[{steps:8,root:62}]),
  route(play("d-degree-walk","Same numbers, new sounds","Take the tune to D","Play 1–2–3–2–1 in D: D–E–F♯–E–D. Compare it with the degree walk in C. The note names changed while the relationships stayed the same. Hum the little phrase before playing.",[62,64,66,64,62]),[{steps:5,root:62}]),
  route(play("twinkle-d-notes","Twinkle: learn the new home slowly","Take the tune to D","Move the two Twinkle phrases to D. Start D–D–A–A–B–B–A, then answer G–G–F♯–F♯–E–E–D. These are the same degree numbers as before. Practice either phrase separately before joining them; there is no clock.",dTwinkle),[{steps:14,root:62}]),
  {id:"degree-playground",title:"Invent a little answer in D",section:"Take the tune to D",kind:"exploration",instruction:"For 45 seconds, choose two or three notes from D major and make a short question. Repeat it with a different ending, finishing on home D when you want it to sound settled. D, F♯, and A are highlighted as the 1, 3, and 5 landmarks. There is no score or required sequence. Keep one idea to play again next time.",targets:[],exploration:{durationSeconds:45,min:62,max:74,pitchClasses:[1,2,4,6,7,9,11],highlighted:[62,66,69]},assessment:{graded:false}},
  route(timed(play("twinkle-d-rehearsal","Twinkle in D: a relaxed rehearsal","Your scale in music","Play the same two phrases at 60 BPM. Let the opening A and final D ring for two beats. Use Step or a slower tempo if the new route needs time, then return to 60. Today you are joining a familiar rhythm to the new key.",dTwinkle),twinkleBeats,60),[{steps:14,root:62}]),
  {...route(timed(play("scale-checkpoint","Twinkle in D: your performance","Your scale in music","Play the same phrase at 70 BPM for two clean runs. You can complete with hints, then press yellow Repeat without hints for a memory run when ready. Notice how the same tune and degree pattern found a new home. Finish by replaying your favorite phrase; next visit, recall it before listening.",dTwinkle),twinkleBeats,70),[{steps:14,root:62}]),repetitions:2},
],2);

/** Learner order; built-ins use the same portable format as authored courses. */
export const builtinCourses = [firstStepsCourse,movementCourse,rhythmCourse,majorScaleCourse] as const;
export const defaultCourse = firstStepsCourse;
